### PR TITLE
Update cyberthunder.php

### PR DESCRIPTION
**Pull request by Owoeye1321**

### CODE REVIEW

**Comment by Owoeye1321** [comment]
Please I've been on this since yesterday night🙏🙏🙏..
My updates are not reflecting in the server as pass its still fail...
Please check my code and mail my status to me😥😥😥

**Comment by daniel23ai** [comment]
I just merged you now
But let me check

**Comment by Owoeye1321** [comment]
I've found the issue.
Please merge owoeye_script.php..
Update the server..

The issue will be solved
Thanks for your concern...

**Comment by daniel23ai** [comment]
I told you it has been merged successfully
 Do me on stack

**Pull request merged**
